package model.paintStrategy;

import java.awt.geom.AffineTransform;

import model.paint.*;
import model.shape.*;

/**
 * Paint a polygon generated by Fish1PolygonFactory
 */
public class Fish1PaintStrategy extends ShapePaintStrategy{

	/**
	 * No-parameter constructor, use a new affine transform
	 */
	public Fish1PaintStrategy() {
		super(new AffineTransform(), new Fish1PolygonFactory().makeShape(0, 0, 1, 1));
	}
	
	/**
	 * Constructor, use an external AffineTransform
	 * @param at - The AffineTransform to use.
	 */
	public Fish1PaintStrategy(AffineTransform at) {
		super(at, new Fish1PolygonFactory().makeShape(0, 0, 1, 1));
	}

}
