package model.paintStrategy;

import java.awt.geom.AffineTransform;

import model.shape.*;
import model.paint.*;
/**
 * Paint a polygon generated by Fish2PolygonFactory
 */
public class Fish2PaintStrategy extends ShapePaintStrategy{

	/**
	 * No-parameter constructor, use a new affine transform
	 */
	public Fish2PaintStrategy() {
		super(new AffineTransform(), new Fish2PolygonFactory().makeShape(0, 0, 1, 1));
	}
	
	/**
	 * Constructor, use an external AffineTransform
	 * @param at - The AffineTransform to use.
	 */
	public Fish2PaintStrategy(AffineTransform at) {
		super(at, new Fish2PolygonFactory().makeShape(0, 0, 1, 1));

	}

}
